from dydx3.constants import API_HOST_MAINNET
from decouple import config

# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated Pairs
FIND_COINTEGRATED = True

# Manage Exits
MANAGE_EXITS = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 5
USD_MIN_COLLATERAL = 180

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

# Ethereum Address
ETHEREUM_ADDRESS = "0xEe2FCa2e5fDf5BcC84c032Bb1F3A45f65E053b77"
#ETHEREUM_ADDRESS = "0xcf6229CA122C5090BDD28613793aDe173963Ab9c"

# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")


# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET

# HOST - Export
HOST = API_HOST_MAINNET 

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/lipm9EUaoJmbB8n147qBw5XL--e9neHz"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET
